version: "3.5"

networks:
  chicken:

services:
  e-chicken-cinema:
    container_name: "e-chicken-cinema"
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - LD_LIBRARY_PATH=/opt/vc/lib
    volumes:
      - /opt/vc:/opt/vc:ro
    privileged: true
    networks:
      - chicken
